vich_uploader:
    db_driver: orm

    mappings:
        project_photos:
            uri_prefix: '%photos_directory%'
            upload_destination: '%kernel.project_dir%/public/%photos_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true